apiVersion: apps/v1
kind: Deployment
metadata:
  name: workmates-deployment
  labels:
    app: workmates-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workmates
  template:
    metadata:
      labels:
        app: workmates
    spec:
      containers:
      - name: workmates-container
        image: facundor/workmates:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERS_API_URL
          value: "http://hello-ms.k8s.fluxit.com.ar/users"